highlighter: pygments
safe: true
lsi: false

title: 'Say What?'

defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
      type: 'posts' # previously `post` in Jekyll 2.2.
    values:
      layout: 'post'

prose:
  rooturl: '_posts'
  siteurl: 'https://liias.github.io/'
  media: 'media'
  metadata:
    _posts:
      - name: 'title'
        field:
          element: 'text'
          label: 'title'