highlighter: pygments
safe: true
lsi: false

siteurl: 'https://liias.github.io'

title: 'Say What?'
excerpt_separator: <!--more-->
permalink: '/:year/:month/:title'

defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
      type: 'posts'
    values:
      layout: 'post'
  -
    scope:
      path: ''
      type: 'drafts'
    values:
      layout: 'post'

prose:
  rooturl: '_posts'
  siteurl: 'https://liias.github.io/'
  media: 'media'
  metadata:
    _posts:
      - name: 'title'
        field:
          element: 'text'
          label: 'title'
